SELECT KR1.KB_REGN_NM, KR2.KB_REGN_NM, KR3.KB_REGN_NM, KC.CMPL_YYMM, KC.CMPX_IDF_NM, KCT.HOUSE_TYP_NM, KCTMP.GNRL_AVG_PRC, KCTMP.GNRL_JS_AVG_PRC
FROM KMIG_KB_REGN KR1
INNER JOIN KMIG_KB_REGN KR2
ON KR1.KB_REGN_CD = KR2.UP_KB_REGN_CD
INNER JOIN KMIG_KB_REGN KR3
ON KR2.KB_REGN_CD = KR3.UP_KB_REGN_CD
INNER JOIN KMIG_KB_CMPX KC
ON KR3.KB_REGN_CD = KC.KB_REGN_CD
INNER JOIN KMIG_KB_CMPX_TYP KCT
ON KC.CMPX_IDF_ID = KCT.CMPX_IDF_ID
INNER JOIN KMIG_KB_CMPX_TYP_MON_PRC KCTMP
ON KCT.CMPX_IDF_ID = KCTMP.CMPX_IDF_ID
AND KCT.HOUSE_TYP_SEQ = KCTMP.HOUSE_TYP_SEQ
AND KCTMP.STD_YYMM = '201803'
WHERE 1=1
AND KR1.KB_REGN_CD IN ('010000','020000','030000')
AND KCTMP.GNRL_AVG_PRC - KCTMP.GNRL_JS_AVG_PRC < 5000
ORDER BY GNRL_AVG_PRC DESC
;

