SELECT KR1.KB_REGN_NM, KR2.KB_REGN_NM, KR3.KB_REGN_NM, KC.CMPX_IDF_NM, KCT.HOUSE_TYP_NM, KCTMP.GNRL_AVG_PRC, KCTMP.GNRL_JS_AVG_PRC
FROM KMIG_KB_REGN KR1
INNER JOIN kmig_kb_regn KR2
ON KR1.KB_REGN_CD = KR2.UP_KB_REGN_CD
INNER JOIN kmig_kb_regn KR3
ON KR2.KB_REGN_CD = KR3.UP_KB_REGN_CD
INNER JOIN KMIG_KB_CMPX KC
ON KR3.KB_REGN_CD = KC.KB_REGN_CD
INNER JOIN KMIG_KB_CMPX_TYP KCT
ON KC.CMPX_IDF_ID = KCT.CMPX_IDF_ID
INNER JOIN KMIG_KB_CMPX_TYP_MON_PRC KCTMP
ON KCT.CMPX_IDF_ID = KCTMP.CMPX_IDF_ID
AND KCT.HOUSE_TYP_SEQ = KCTMP.HOUSE_TYP_SEQ
AND KCTMP.GNRL_AVG_PRC - KCTMP.GNRL_JS_AVG_PRC < 5000
AND KCTMP.STD_YYMM = '201711'
WHERE KR1.KB_REGN_CD = '010000'
ORDER BY GNRL_AVG_PRC DESC
;

SELECT *
FROM KMIG_KB_REGN KR1
   , kmig_kb_regn KR2
WHERE KR1.KB_REGN_CD = KR2.UP_KB_REGN_CD



;
SELECT *
FROM KMIG_KB_CMPX_TYP

;

SELECT COUNT(*)
FROM KMIG_KB_CMPX_TYP_MON_PRC
WHERE STD_YYMM = '201711'
;
SELECT *
FROM KMIG_KB_CMPX
#WHERE CMPX_IDF_ID = 'KBA000001'
WHERE CMPX_IDF_NM LIKE '%미진동백%'
;
SELECT * FROM KMIG_KB_CMPX_TYP_MON_PRC
WHERE CMPX_IDF_ID < 'KBA001000'
ORDER BY CMPX_IDF_ID ASC, HOUSE_TYP_SEQ ASC, STD_YYMM ASC 
;

SELECT NOW()
;
SELECT *
FROM KMIG_KB_CMPX_TYP


;

SELECT *
FROM KMIG_KB_CMPX
WHERE CMPX_IDF_ID IN (	SELECT CMPX_IDF_ID	FROM KMIG_KB_CMPX_TYP_MON_PRC	GROUP BY CMPX_IDF_ID	HAVING MAX(STD_YYMM) < '201711')    


;

SELECT *
FROM KADM_ACT_FUNC
WHERE USE_YN


;

SELECT a.CMPX_IDF_ID, a.HOUSE_TYP_SEQ, b.KB_REGN_CD as SMALL_KB_REGN_CD FROM KMIG_KB_CMPX_TYP a, kmig_kb_cmpx b where a.cmpx_idf_id = b.cmpx_idf_id AND a.CMPX_IDF_ID NOT IN (SELECT CMPX_IDF_ID	FROM KMIG_KB_CMPX_TYP_MON_PRC	GROUP BY CMPX_IDF_ID	HAVING MAX(STD_YYMM) < '201711') ORDER BY CMPX_IDF_ID ASC, a.HOUSE_TYP_SEQ