UPDATE kmig_kb_prc_stat
SET 3M_RISE_PRC = 3M_GAP
  , 3M_GAP = 3M_RISE_PRC
  , 3Y_RISE_PRC = 3Y_GAP
  , 3Y_GAP = 3Y_RISE_PRC
  , 4Y_RISE_PRC = 4Y_GAP
  , 4Y_GAP = 4Y_RISE_PRC
  , 5Y_RISE_PRC = 5Y_GAP
  , 5Y_GAP = 5Y_RISE_PRC
  , 10Y_RISE_PRC = 10Y_GAP
  , 10Y_GAP = 10Y_RISE_PRC  
  , CHG_USER_ID = 1000000001
  , CHG_DTM = NOW()
WHERE CMPX_IDF_ID BETWEEN 'KBA020001' AND 'KBA030000'  
;
select * FROM kmig_kb_prc_stat
WHERE STD_YYMM = '201711'
oRDER BY GNRL_JS_AVG_PRC/GNRL_AVG_PRC  DESC 
;
UPDATE kmig_kb_prc_stat KCTMP
SET 6M_PRC = (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP6M WHERE KCTMP.CMPX_IDF_ID = KCTMP6M.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCTMP6M.HOUSE_TYP_SEQ AND (CASE WHEN  SUBSTR(KCTMP.STD_YYMM - 6,5,2)  = '00' THEN KCTMP.STD_YYMM - 6 - 88 WHEN SUBSTR(KCTMP.STD_YYMM - 6,5,2)  > '12' THEN KCTMP.STD_YYMM - 6 - 88 ELSE KCTMP.STD_YYMM - 6 END) = KCTMP6M.STD_YYMM)
  , 6M_JS_PRC = (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP6M WHERE KCTMP.CMPX_IDF_ID = KCTMP6M.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCTMP6M.HOUSE_TYP_SEQ AND (CASE WHEN  SUBSTR(KCTMP.STD_YYMM - 6,5,2)  = '00' THEN KCTMP.STD_YYMM - 6 - 88 WHEN SUBSTR(KCTMP.STD_YYMM - 6,5,2)  > '12' THEN KCTMP.STD_YYMM - 6 - 88 ELSE KCTMP.STD_YYMM - 6 END) = KCTMP6M.STD_YYMM)
  , CHG_USER_ID = 1000000001
  , CHG_DTM = NOW()
WHERE CMPX_IDF_ID BETWEEN 'KBA005001' AND 'KBA008000'    
;
  
UPDATE  kmig_kb_prc_stat
SET
#SELECT 
 6M_GAP = 6M_PRC - 6M_JS_PRC
,6M_RISE_PRC = GNRL_AVG_PRC - 6M_PRC
,6M_ROR = GNRL_AVG_PRC/6M_PRC - 1
,6M_GAP_ROR = (GNRL_AVG_PRC - 6M_PRC)/(6M_PRC - 6M_JS_PRC)
, CHG_USER_ID = 1000000001
, CHG_DTM = NOW()
WHERE CMPX_IDF_ID BETWEEN 'KBA020001' AND 'KBA030000'  
;

SELECT * FROM kmig_kb_prc_stat


