UPDATE
#SELECT * FROM 
KMIG_KB_CMPX_TYP
SET SPLY_AERA = CAST(LEFT(HOUSE_TYP_NM,INSTR(HOUSE_TYP_NM,'㎡')-1) AS DECIMAL(10,2))
  , ONLY_AERA = CAST(REPLACE(MID(HOUSE_TYP_NM,INSTR(HOUSE_TYP_NM,'/')+1,100),'㎡','') AS DECIMAL(10,2))
  , CHG_USER_ID = 1000000001
  , CHG_DTM = NOW()
;
  


select HOUSE_TYP_NM
	 , LEFT(HOUSE_TYP_NM,INSTR(HOUSE_TYP_NM,'㎡')-1)
     , REPLACE(MID(HOUSE_TYP_NM,INSTR(HOUSE_TYP_NM,'/')+1,100),'㎡','')
	 , CAST(LEFT(HOUSE_TYP_NM,INSTR(HOUSE_TYP_NM,'㎡')-1) AS DECIMAL(10,2))
     , CAST(REPLACE(MID(HOUSE_TYP_NM,INSTR(HOUSE_TYP_NM,'/')+1,100),'㎡','') AS DECIMAL(10,2))
     , ONLY_AERA
     , SPLY_AERA
from KMIG_KB_CMPX_TYP
;
ALTER TABLE KMIG_KB_CMPX_TYP CHANGE ONLY_AERA ONLY_AREA FLOAT(10,2);
ALTER TABLE KMIG_KB_CMPX_TYP CHANGE SPLY_AERA SPLY_AREA FLOAT(10,2);
;
SELECT * FROM KMIG_NV_CMPX_TYP
;

ALTER TABLE KMIG_NV_CMPX_TYP CHANGE SPLY_AERA_NUM SPLY_AREA_NUM FLOAT(10,2);
;


ALTER TABLE KMIG_NV_CMPX_TYP DROP COLUMN ONLY_AREA_NUM;
ALTER TABLE KMIG_NV_CMPX_TYP DROP COLUMN ONLY_SPLY_NUM;
ALTER TABLE KMIG_NV_CMPX_TYP ADD COLUMN SPLY_AERA_NUM FLOAT(10,2);
ALTER TABLE KMIG_NV_CMPX_TYP ADD COLUMN SPLY_AERA_NUM FLOAT(10,2);
ALTER TABLE KMIG_KB_CMPX_TYP ADD COLUMN SPLY_AERA_NUM FLOAT(10,2);
SELECT * FROM KMIG_KB_CMPX_TYP 
;
#네이버 전용면적 및 공급면적 숫자타입으로 변경
#SELECT * FROM 
UPDATE
KMIG_NV_CMPX_TYP
SET SPLY_AERA_NUM = CAST(REPLACE(SPLY_AERA,'㎡','')AS DECIMAL(10,2))
  , ONLY_AREA_NUM = CAST(REPLACE(ONLY_AERA,'㎡','')AS DECIMAL(10,2))
  , CHG_USER_ID = 1000000001
  , CHG_DTM = NOW()
;

SELECT * FROM KMIG_NV_CMPX_TYP
