SELECT *
FROM  (
	SELECT STD_YYMM, MAX(3M_ROR) MAX_3M_ROR
	FROM KMIG_KB_PRC_STAT
	WHERE STD_YYMM BETWEEN '200404' AND '201712'
	GROUP BY STD_YYMM
) B
INNER JOIN KMIG_KB_PRC_STAT A
ON A.STD_YYMM = B.STD_YYMM
AND A.3M_ROR = B.MAX_3M_ROR
ORDER BY A.STD_YYMM DESC
;
