SELECT  MIN(REG_DTM)
     , MAX(REG_DTM) 
     , MAX(CMPX_IDF_ID)
     , TIMESTAMPDIFF(SECOND,MIN(REG_DTM),MAX(REG_DTM)) 소요시간초
     , (SELECT COUNT(*) FROM (SELECT DISTINCT CMPX_IDF_ID FROM KMIG_KB_CMPX_TYP_MON_PRC WHERE CMPX_IDF_ID > 'KBA007074') A) 단지갯수
     , (SELECT COUNT(*) FROM (SELECT DISTINCT CMPX_IDF_ID FROM KMIG_KB_CMPX_TYP_MON_PRC WHERE CMPX_IDF_ID > 'KBA007074') A)/TIMESTAMPDIFF(SECOND,MIN(REG_DTM),MAX(REG_DTM))*3600 시간당단지수
FROM KMIG_KB_CMPX_TYP_MON_PRC WHERE CMPX_IDF_ID > 'KBA007074'
;
SELECT  MIN(REG_DTM)
     , MAX(REG_DTM) 
     , TIMESTAMPDIFF(SECOND,MIN(REG_DTM),MAX(REG_DTM)) 소요시간초
     , (SELECT COUNT(*) FROM (SELECT DISTINCT CMPX_IDF_ID FROM KMIG_KB_CMPX_TYP_MON_PRC WHERE CMPX_IDF_ID BETWEEN 'KBA000884' AND 'KBA005624') A) 단지갯수
     , (SELECT COUNT(*) FROM (SELECT DISTINCT CMPX_IDF_ID FROM KMIG_KB_CMPX_TYP_MON_PRC WHERE CMPX_IDF_ID BETWEEN 'KBA000884' AND 'KBA005624') A)/TIMESTAMPDIFF(SECOND,MIN(REG_DTM),MAX(REG_DTM))*3600 시간당단지수
FROM KMIG_KB_CMPX_TYP_MON_PRC WHERE CMPX_IDF_ID BETWEEN 'KBA000884' AND 'KBA005624'
;
select max(cmpx_idf_id), count(*)
from kmig_kb_cmpx
;

SELECT *
FROM KMIG_KB_CMPX_TYP KCT
LEFT OUTER JOIN KMIG_KB_CMPX_TYP_MON_PRC KCTMP
ON KCT.CMPX_IDF_ID = KCTMP.CMPX_IDF_ID 
AND KCT.HOUSE_TYP_SEQ = KCTMP.HOUSE_TYP_SEQ 
WHERE KCTMP.CMPX_IDF_ID IS NULL