SELECT KC.CMPX_IDF_NM
	, KCT.HOUSE_TYP_NM
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201701' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201701매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201702' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201702매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201703' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201703매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201704' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201704매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201705' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201705매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201706' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201706매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201707' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201707매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201708' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201708매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201709' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201709매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201710' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201710매매가
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201711' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201711매매가	
	, (SELECT GNRL_AVG_PRC FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP WHERE KCTMP.STD_YYMM = '201712' AND KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ) AS 201712매매가	
FROM KMIG_KB_REGN KR
INNER JOIN KMIG_KB_CMPX KC
ON KR.KB_REGN_CD = KC.KB_REGN_CD
INNER JOIN KMIG_KB_CMPX_TYP KCT
ON KC.CMPX_IDF_ID = KCT.CMPX_IDF_ID
AND KCT.ONLY_AERA BETWEEN 80 AND 90
/*INNER JOIN KMIG_KB_CMPX_TYP_MON_PRC KCTMP
ON KCT.CMPX_IDF_ID = KCTMP.CMPX_IDF_ID
AND KCT.HOUSE_TYP_SEQ = KCTMP.HOUSE_TYP_SEQ*/
WHERE KR.UP_KB_REGN_CD = '023000'
ORDER BY CMPX_IDF_NM, KCT.HOUSE_TYP_SEQ
;