/* 실거래가 DATA 검증 */
#PK는 무엇인가?
SELECT GOV_LEGL_DONG_CD, DEAL_YYMM, DEAL_AMT, ROAD_NM, ROAD_NM_CMPX_ORGL_NUM_CD, ROAD_NM_CMPX_VICE_NUM_CD, LEGL_DONG_NM, REAL_DEAL_CMPX_NM, DEAL_YMD, ONLY_AREA, DEAL_YMD, HNUM, FLR
FROM KMIG_DEAL_DTL DD1
WHERE EXISTS(
	SELECT 1
    FROM KMIG_DEAL_DTL DD2
    WHERE DD1.GOV_LEGL_DONG_CD = DD2.GOV_LEGL_DONG_CD
    AND DD1.ROAD_NM = DD2.ROAD_NM
    AND DD1.ROAD_NM_CMPX_ORGL_NUM_CD = DD2.ROAD_NM_CMPX_ORGL_NUM_CD
    AND DD1.ROAD_NM_CMPX_VICE_NUM_CD = DD2.ROAD_NM_CMPX_VICE_NUM_CD
    AND DD1.REAL_DEAL_CMPX_NM != DD2.REAL_DEAL_CMPX_NM
)
ORDER BY GOV_LEGL_DONG_CD, ROAD_NM, ROAD_NM_CMPX_ORGL_NUM_CD, ROAD_NM_CMPX_VICE_NUM_CD, DEAL_YYMM DESC

;

SELECT * 
FROM KMIG_BB_CMPX BC
LEFT OUTER JOIN KMIG_BB_REGN_CMPX_REL BRCR
ON BC.BB_CMPX_ID = BRCR.BB_CMPX_ID
WHERE BRCR.BB_CMPX_ID IS NULL
;


SELECT *
FROM KMIG_BB_REGN_CMPX_REL

;

