SELECT KR2_KB_REGN_NM, AVG(전세가율)
FROM (
	SELECT 
		   KCTMP.STD_YYMM
		 , KR1.KB_REGN_NM DDD
		 , KR2.KB_REGN_NM KR2_KB_REGN_NM
		 , KR3.KB_REGN_NM CCC
		 , KC.CMPX_IDF_NM
		 , KCT.HOUSE_TYP_NM
		 , KC.CMPL_YYMM
		 , GNRL_JS_AVG_PRC/GNRL_AVG_PRC*100 전세가율
		 , GNRL_JS_AVG_PRC
		 , GNRL_AVG_PRC
         , KC.TOT_HSHL_CNT
	FROM KMIG_KB_CMPX_TYP_MON_PRC KCTMP
	INNER JOIN (
		SELECT MIN(STD_YYMM) STD_YYMM, B.CMPX_IDF_ID, B.HOUSE_TYP_SEQ
		  FROM KMIG_KB_CMPX_TYP_MON_PRC B
		  INNER JOIN (
				SELECT A.CMPX_IDF_ID, A.HOUSE_TYP_SEQ, FLOOR(MIN(A.GNRL_JS_AVG_PRC/A.GNRL_AVG_PRC)*100) JSY, A.GNRL_JS_AVG_PRC, A.GNRL_AVG_PRC
				FROM KMIG_KB_CMPX C
				INNER JOIN KMIG_KB_CMPX_TYP_MON_PRC A
				ON C.CMPX_IDF_ID = A.CMPX_IDF_ID		
				WHERE C.TOT_HSHL_CNT > 500
				AND C.CMPL_YYMM > '199900'
                AND C.CMPL_YYMM < '201099'
				AND A.STD_YYMM > '200400'
				AND A.GNRL_AVG_PRC != 0
				AND A.GNRL_JS_AVG_PRC != 0
				GROUP BY CMPX_IDF_ID, HOUSE_TYP_SEQ
		) AA
		ON B.CMPX_IDF_ID = AA.CMPX_IDF_ID
		AND B.HOUSE_TYP_SEQ = AA.HOUSE_TYP_SEQ
		AND FLOOR(B.GNRL_JS_AVG_PRC/B.GNRL_AVG_PRC*100) = AA.JSY
		WHERE B.STD_YYMM > '200400'
		AND B.GNRL_AVG_PRC != 0
		AND B.GNRL_JS_AVG_PRC != 0
		GROUP BY B.CMPX_IDF_ID, B.HOUSE_TYP_SEQ
	) BB
	ON KCTMP.STD_YYMM = BB.STD_YYMM
	AND KCTMP.CMPX_IDF_ID = BB.CMPX_IDF_ID
	AND KCTMP.HOUSE_TYP_SEQ = BB.HOUSE_TYP_SEQ
	INNER JOIN KMIG_KB_CMPX_TYP KCT
	ON KCTMP.CMPX_IDF_ID = KCT.CMPX_IDF_ID
	AND KCT.ONLY_AREA BETWEEN 80 AND 90
	AND KCTMP.HOUSE_TYP_SEQ = KCT.HOUSE_TYP_SEQ
	INNER JOIN KMIG_KB_CMPX KC
	ON KCTMP.CMPX_IDF_ID = KC.CMPX_IDF_ID
	AND KC.CMPL_YYMM > '199000'
    AND KC.CMPL_YYMM < '201099'    
	AND KC.TOT_HSHL_CNT > 500
	INNER JOIN KMIG_KB_REGN KR3
	ON KC.KB_REGN_CD = KR3.KB_REGN_CD
	INNER JOIN KMIG_KB_REGN KR2
	ON KR3.UP_KB_REGN_CD = KR2.KB_REGN_CD
	INNER JOIN KMIG_KB_REGN KR1
	ON KR2.UP_KB_REGN_CD = KR1.KB_REGN_cD
	WHERE KCTMP.STD_YYMM > '200400'
	AND KCTMP.STD_YYMM < '201099'    
	AND KCTMP.GNRL_AVG_PRC != 0
	AND KCTMP.GNRL_JS_AVG_PRC != 0
)     A
GROUP BY KR2_KB_REGN_NM
ORDER BY AVG(전세가율)
