INSERT INTO kmig_kb_cmpx_typ_now_prc_stat
SELECT 
 KC.CMPX_IDF_ID
,KCT.HOUSE_TYP_SEQ
,KC.CMPX_IDF_NM
,KC.GOV_LEGL_DONG_CD
,KC.KB_CMPX_KND
,KC.TOT_HSHL_CNT
,KC.MVIT_YYMM
,KC.CMPL_YYMM
,KC.HSHL_PER_PARK_CNT_RATE
,KC.TOT_DONG_CNT
,KC.X_COOR_VAL
,KC.Y_COOR_VAL
,KC.HNUM_ADDR
,KC.ROAD_NM_ADDR
,KC.DTL_HNUM_CNTS
,KC.IMG_CNT
,KC.IMG_NM
,KC.IMG_FILE_NM
,KC.IMG_DIR_CORS_CNTS
,KC.MIN_AREA
,KC.MBIG_AREA
,KC.DEL_YN
,KC.PRC_CMPX_IDF_ID
,GLD.GOV_LEGL_DONG_NM
,GLD.UP_GOV_LEGL_DONG_CD
,GLD.GRD
,GLD.REG_YMD
,GLD.CLOS_YMD
,GLD.FINL_JOB_YMD
,GLD.LWST_REGN_NM
,GLD.GOV_RSDT_LEGL_DONG_CD
,GLD.LEGL_JIJC_LEGL_DONG_CD
,KCT.HOUSE_TYP_NM
,KCT.HOUSE_TYP_RPSN_NM
,KCT.ONLY_AREA
,KCT.SPLY_AREA
,KCTMP.STD_YYMM
,KCTMP.UP_AVG_PRC
,KCTMP.GNRL_AVG_PRC
,KCTMP.DOWN_AVG_PRC
,KCTMP.UP_JS_AVG_PRC
,KCTMP.GNRL_JS_AVG_PRC
,KCTMP.DOWN_JS_AVG_PRC
,KCTMP.GNRL_GAP_PRC
,1000000001
,NOW()
,1000000001
,NOW()
,GNRL_AVG_PRC/SPLY_AREA*3.3
,GNRL_JS_AVG_PRC/SPLY_AREA*3.3
FROM KMIG_KB_CMPX KC
INNER JOIN kmig_gov_legl_dong GLD
ON KC.GOV_LEGL_DONG_CD = GLD.GOV_LEGL_DONG_CD
INNER JOIN KMIG_KB_CMPX_TYP KCT
ON KC.PRC_CMPX_IDF_ID = KCT.CMPX_IDF_ID
INNER JOIN  KMIG_KB_CMPX_TYP_MON_PRC  KCTMP
ON KCT.CMPX_IDF_ID = KCTMP.CMPX_IDF_ID 
AND KCT.HOUSE_TYP_SEQ = KCTMP.HOUSE_TYP_SEQ
AND KCTMP.STD_YYMM = '201910'
WHERE 1=1
#WHERE KC.GOV_LEGL_DONG_CD LIKE '11%'
AND KC.CMPX_IDF_ID NOT IN (
	SELECT CMPX_IDF_ID
	FROM kmig_kb_cmpx_typ_now_prc_stat
)
#INNER JOIN (SELECT @row_num := 1, @row_value := '') if_table
#order by SUBSTRING(GLD.GOV_LEGL_DONG_CD,1,5), KCTMP.GNRL_AVG_PRC/KCT.SPLY_AREA
   
;
#MIG 검증 
SELECT *
FROM KMIG_KB_CMPX KC
WHERE NOT EXISTS(
	SELECT 1
    FROM kmig_kb_cmpx_typ_now_prc_stat STS
    WHERE STS.CMPX_IDF_ID = KC.CMPX_IDF_ID
)
AND LENGTH(PRC_CMPX_IDF_ID) > 0
;