def initializeTableDic(dicTable): #ERROR INFO Debug
    for dicName in dicTable.keys():
        dicTable[dicName] = ''

dicTable = {
    'KMIG_NV_CMPX' :
        {
            'NV_CMPX_ID': None,
            'NV_CMPX_NM': None,
            'GOV_LEGL_DONG_CD': None,
            'NV_CMPX_KND': None,
            'BAS_ADDR': None,
            'DTL_ADDR': None,
            'ROAD_NM_BAS_ADDR' : None,
            'ROAD_NM_DTL_ADDR' : None,
            'ADDR' : None,
            'X_COOR_VAL': None,
            'Y_COOR_VAL': None,
            'TOT_HSHL_CNT': None,
            'TOT_RENT_HSHL_CNT': None,
            'TOT_DONG_CNT': None,
            'MAX_FLR': None,
            'MIN_FLR': None,
            'CMPL_YYMM': None,
            'SALE_CNT': None,
            'JS_CNT': None,
            'WS_CNT': None,
            'SHRT_RENT_CNT': 0,
            'BLD_CO_NM': None,
            'TOT_PARK_CNT': 0,
            'HSHL_PER_PARK_CNT': 0,
            'HEAT_WAY': None,
            'HEAT_FUEL': None,
            'FAR': None,
            'BTLR': None,
            'MBIG_SPLY_AREA' : None,
            'MSML_SPLY_AREA' : None,
            'CMPX_REG_VAL' : None,
            'AREA_LST': None,
            'MGMT_CO_TEL': None,
            'SBWY_INFO': None,
            'WASP_PIPE_RPLC': None,
            'MIG_RSN': None,
            'WHL_DONG_CNT' : None,
            'BMAK_YN' : None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    ,
    'KMIG_NV_CMPX_IMG' :
        {
            'NV_CMPX_ID': None,
            'IMG_CORS': None,
            'IMG_ID': None,
            'NEW_OLD_CL': None,
            'IMG_CTGR_NM': None,
            'IMG_DESC': None,
            'IMG_REG_DTM':None,
            'IMG_SORT': None,
            'IMG_KEY_SEQ':None,
            'IMG_TYP_CD':None,
            'ETC_ITEM_NM':None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    ,'KMIG_NV_CMPX_RBLD' :
        {
            'NV_CMPX_ID': None,
            'BIZ_STEP': None,
            'CHC_BLD_CO': None,
            'EXP_HSHL_CNT': None,
            'EXP_FAR': None,
            'GULD_TEL': None,
            'EXP_ASGN_AREA_STR': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    ,'KMIG_NV_CMPX_TYP' :
        {
            'NV_CMPX_ID': None,
            'NV_CMPX_TYP_SEQ': None,
            'CMPX_TYP_NM': None,
            'SPLY_AREA': None,
            'ONLY_AREA': None,
            'DOOR_STRC': None,
            'ROOM_CNT_STR': None,
            'BATH_CNT_STR': None,
            'SOH_HSHL_CNT': None,
            'SPLY_AREA_NUM': None,
            'ONLY_AREA_NUM': None,
            'RET_TYP_CD': None,
            'AVG_MNTN_AMT': None,
            'SMMR_MNTN_AMT': None,
            'WNTR_MNTN_AMT': None,
            'DEAL_LMIT_YMD': None,
            'DEAL_PSBL_YMD': None,
            'DCNT_PRC_STR' : None,
            'DCNT_PRC_LTR_STR' : None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None,
        }
    ,'KMIG_NV_CMPX_TYP_IMG' :
        {
            'NV_CMPX_ID' : None,
            'NV_CMPX_TYP_SEQ' : None,
            'IMG_ID' : None,
            'IMG_SORT' : None,
            'IMG_CORS' : None,
            'IMG_TYP_CD' : None,
            'REG_USER_ID' : None,
            'REG_DTM' : None,
            'CHG_USER_ID' : None,
            'CHG_DTM' : None,
        }
    ,'KMIG_NV_CMPX_TYP_STAT' :
        {
            'NV_CMPX_ID': None,
            'NV_CMPX_TYP_SEQ': None,
            'SALE_CNT': None,
            'JS_CNT': None,
            'WS_CNT': None,
            'SHRT_RENT_CNT': None,
            'MSML_PRC_AMT_STR': None,
            'MBIG_PRC_AMT_STR': None,
            'MSML_PYNG_PER_AMT_STR': None,
            'MBIG_PYNG_PER_AMT_STR': None,
            'AMT_STR': None,
            'PYNG_PER_AMT_STR': None,
            'JS_PRC_STR': None,
            'JS_PYNG_PER_PRC_STR': None,
            'JS_PRC_RATE_STR': None,
            'JS_PRC_MSML_AMT_STR': None,
            'JS_PRC_MBIG_AMT_STR': None,
            'JS_PYNG_PER_MSML_PRC_STR': None,
            'JS_PYNG_PER_MBIG_PRC_STR': None,
            'JS_PRC_MSML_PRC_STR': None,
            'JS_PRC_RATE_MBIG_PRC_STR': None,
            'WS_PRC_STR': None,
            'WS_DPST_MSML_AMT_STR': None,
            'WS_MSML_PRC_STR': None,
            'WS_DPST_MBIG_AMT_STR': None,
            'WS_MBIG_PRC_STR': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    ,'KADM_JOB_EXEC' :
        {
            'JOB_ID' : None,
            'EXEC_DTM' : None,
            'EXEC_STAT_CD' : None,
            'STA_DTM' : None,
            'END_DTM' : None,
            'EXEC_PARM1' : None,
            'EXEC_PARM2' : None,
            'EXEC_PARM3' : None,
            'EXEC_PARM4' : None,
            'EXEC_PARM5' : None,
            'EXEC_PARM6' : None,
            'EXEC_PARM7' : None,
            'EXEC_PARM8' : None,
            'EXEC_PARM9' : None,
            'EXEC_PARM10' : None,
            'REG_USER_ID' : None,
            'REG_DTM' : None,
            'CHG_USER_ID' : None,
            'CHG_DTM' : None
        }
    ,'KADM_JOB_FUNC_EXEC':
        {
            'JOB_ID': None,
            'ACT_ID': None,
            'FUNC_ID': None,
            'EXEC_DTM' : None,
            'EXEC_STAT_CD' : None,
            'STA_DTM' : None,
            'END_DTM' : None,
            'EXEC_PARM1' : None,
            'EXEC_PARM2' : None,
            'EXEC_PARM3' : None,
            'EXEC_PARM4' : None,
            'EXEC_PARM5' : None,
            'EXEC_PARM6' : None,
            'EXEC_PARM7' : None,
            'EXEC_PARM8' : None,
            'EXEC_PARM9' : None,
            'EXEC_PARM10' : None,
            'REG_USER_ID' : None,
            'REG_DTM' : None,
            'CHG_USER_ID' : None,
            'CHG_DTM' : None
        }
    ,'KADM_JOB_SCHD':
        {
            'JOB_ID' : None,
            'JOB_SEQ' : None,
            'EXEC_PERD_CD' : None,
            'EXEC_MM' : None,
            'EXEC_DD' : None,
            'EXEC_HH' : None,
            'EXEC_MI' : None,
            'EXEC_DAY_CD' : None,
            'CYCL_MI' : None,
            'IMDI_EXEC_YN' : None,
            'USE_YN' : None,
            'DEL_YN' : None,
        }
    , 'KMIG_BB_LV1_REGN':
        {
            'BB_LV1_REGN_CD': None,
            'BB_LV1_REGN_NM': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    , 'KMIG_BB_LV2_REGN':
        {
            'BB_LV1_REGN_CD': None,
            'BB_LV2_REGN_CD': None,
            'BB_LV2_REGN_NM': None,
            'BB_LV1_REGN_NM': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    , 'KMIG_BB_LV3_REGN':
        {
            'BB_LV1_REGN_CD': None,
            'BB_LV2_REGN_CD': None,
            'BB_LV3_REGN_CD': None,
            'BB_LV3_REGN_NM': None,
            'BB_LV1_REGN_NM': None,
            'BB_LV2_REGN_NM': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    , 'KMIG_BB_CMPX':
        {
            'BB_CMPX_ID' : None,
            'BB_CMPX_NM' : None,
            'TOT_HSHL_CNT' : None,
            'CMPL_YYMM' : None,
            'BLD_CO_NM' : None,
            'TOT_DONG_FLR_NM' : None,
            'TOT_PARK_CNT' : None,
            'HEAT_WAY' : None,
            'REG_USER_ID' : None,
            'REG_DTM' : None,
            'CHG_USER_ID' : None,
            'CHG_DTM' : None
        }
    , 'KMIG_BB_REGN_CMPX_REL':
        {
            'BB_LV1_REGN_CD': None,
            'BB_LV2_REGN_CD': None,
            'BB_LV3_REGN_CD': None,
            'BB_CMPX_ID': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None,
        }
    , 'KMIG_BB_CMPX_TYP':
        {
            'BB_CMPX_ID' : None,
            'BB_CMPX_TYP_SEQ' : None,
            'CMPX_TYP_NM' : None,
            'SPLY_AREA' : None,
            'REG_USER_ID' : None,
            'REG_DTM' : None,
            'CHG_USER_ID' : None,
            'CHG_DTM' : None,
        }
    , 'KMIG_BB_CMPX_TYP_MON_PRC':
        {
            'BB_CMPX_ID' : None,
            'BB_CMPX_TYP_SEQ' : None,
            'STD_YYMM' : None,
            'STD_YMD' : None,
            'DOWN_PRC' : None,
            'UP_PRC' : None,
            'CHG_PRC' : None,
            'DOWN_JS_PRC' : None,
            'UP_JS_PRC' : None,
            'CHG_JS_PRC' : None,
            'REG_USER_ID' : None,
            'REG_DTM' : None,
            'CHG_USER_ID' : None,
            'CHG_DTM' : None
        }
    , 'KMIG_NV_CMPX_ATCL':
        {
            'ATCL_NUM': None,
            'NV_CMPX_ID': None,
            'NV_CMPX_TYP_SEQ': None,
            'NV_CMPX_NM': None,
            'NV_CMPX_KND': None,
            'NV_CMPX_KND_NM': None,
            'CMPX_TYP_NM': None,
            'NV_ATCL_CMPX_TYP_CD': None,
            'SPLY_AREA_STR': None,
            'ONLY_AREA_STR': None,
            'NV_ATCL_STAT_CD': None,
            'NV_ATCL_STAT_NM': None,
            'NV_DEAL_TYP_CD': None,
            'NV_VRFY_TYP_CD': None,
            'FLR_INFO': None,
            'PRC_CHG_STAT_CD': None,
            'PRC_CHG_YN': None,
            'DEAL_PRC_NM': None,
            'PRMU_PRC_NM': None,
            'SAME_ADDR_PRMU_MBIG_PRC_NM': None,
            'SAME_ADDR_PRMU_MSML_PRC_NM' : None,
            'RENT_PRC_NM': None,
            'EXPS_NM': None,
            'ATCL_CHK_YMD': None,
            'DEAL_CMPL_YMD': None,
            'ATCL_DESC': None,
            'DONG_NM': None,
            'SAME_ADDR_CNT': None,
            'SAME_ADDR_DRCT_CNT': None,
            'SAME_ADDR_MBIG_PRC_NM': None,
            'SAME_ADDR_MSML_PRC_NM': None,
            'PRVD_CO_ID': None,
            'PRVD_CO_NM': None,
            'PRVD_ATCL_ADDR': None,
            'PRVD_ATCL_LINK_URL': None,
            'PRVD_ATCL_LINK_TITL_USE_YN': None,
            'PRVD_ATCL_LINK_USE_PRVD_CO_NM_YN': None,
            'PRVD_MBL_ATCL_URL': None,
            'PRVD_MBL_LINK_TITL_USE_YN': None,
            'PRVD_MBL_LINK_PRVD_CO_NM_USE_YN': None,
            'X_COOR_VAL': None,
            'Y_COOR_VAL': None,
            'LOC_MARK_YN': None,
            'LREA_NM': None,
            'LREA_ID': None,
            'DRCT_DEAL_YN': None,
            'SELL_USER_CELL_NUM': None,
            'DTL_ADDR': None,
            'DTL_ADDR_YN': None,
            'OWNER_CHK_YN': None,
            'RPSN_IMG_URL': None,
            'RPSN_IMG_TYP_CD': None,
            'RPSN_IMG_THMB_NM': None,
            'IMG_CNT': None,
            'SELL_USER_NM': None,
            'REAL_DEAL_YYMM': None,
            'REAL_DEAL_YMD_CLCT_CD': None,
            'REAL_DEAL_YMD_CLCT_NM': None,
            'REAL_DEAL_PRC_NM': None,
            'REAL_DEAL_DPST_NM': None,
            'REAL_DEAL_RENT_PRC_NM': None,
            'DEAL_PRC_NUM': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None,
        }
    , 'KMIG_NV_CMPX_ATCL_TAG':
        {
            'ATCL_NUM': None,
            'TAG_NM': None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    ,'KADM_JOB_FUNC_EXEC_MSG':
        {
            'JOB_ID' : None,
            'ACT_ID' : None,
            'FUNC_ID' : None,
            'EXEC_DTM' : None,
            'SEQ' : None,
            'REQ_URL' : None,
            'PAGE_CNTS' : None,
            'ECPT_CNTS' : None,
            'RMK_CNTS' : None,
            'REG_USER_ID': None,
            'REG_DTM': None,
            'CHG_USER_ID': None,
            'CHG_DTM': None
        }
    ,'KMIG_NV_CMPX_TYP_MNTN_PRC':
        {
            'NV_CMPX_ID' : None,
            'NV_CMPX_TYP_SEQ' : None,
            'STD_YYMM' : None,
            'TOT_PRC_NM' : None,
            'REG_USER_ID' : None,
            'REG_DTM' : None,
            'CHG_USER_ID' : None,
            'CHG_DTM' : None
        }
}