SELECT * 
FROM KADM_JOB J
INNER JOIN KADM_JOB_ACT JA
ON J.JOB_ID = JA.JOB_ID
INNER JOIN KADM_ACT A
ON JA.ACT_ID = A.ACT_ID
INNER JOIN KADM_ACT_FUNC AF
ON A.ACT_ID = AF.ACT_ID
INNER JOIN KADM_FUNC F
ON AF.FUNC_ID = F.FUNC_ID
WHERE J.JOB_ID LIKE 'NVDC0`PRIMARY``PRIMARY``PRIMARY``PRIMARY`kmig_nv_sale05'
;
SELECT * FROM KADM_JOB
;


SELECT * FROM KADM_COM_CD_DTL
;


