INSERT INTO KADM_JOB_SCHD(
JOB_ID,
JOB_SEQ,
EXEC_PERD_CD,
EXEC_MM,
EXEC_DD,
EXEC_HH,
EXEC_MI,
EXEC_DAY_CD,
CYCL_MI,
USE_YN,
DEL_YN,
REG_USER_ID,REG_DTM,CHG_USER_ID,CHG_DTM)VALUES('NVIN001','1','DD','','','00','00','','','Y','N',1000000001,NOW(),1000000001,NOW());
;

SELECT * FROM KADM_JOB_SCHD

;

DESC KADM_JOB_FUNC_EXEC