from DAO.KTable import *
from sqlalchemy import Integer, ForeignKey, String
from common.database.testReflect import *
from common.database.repSqlAlchemy import *
import datetime

class LeglDong(Base,KTable):
    __tablename__ = 'kred_legl_dong'

    legl_dong_cd = KColumn(String(10), primary_key = True, nullable = False)
    legl_dong_nm = KColumn(String(200), nullable = True)
    legl_dong_whl_nm = KColumn(String(200), nullable = True)
    up_legl_dong_cd = KColumn(String(10), nullable = True)
    lv_cd = KColumn(String(20), nullable = True)
    sort_seq = KColumn(Integer, nullable = True)
    reg_ymd = KColumn(String(8), nullable = True)
    clos_ymd = KColumn(String(8), nullable = True)
    finl_job_ymd = KColumn(String(8), nullable = True)
    rsdt_legl_dong_cd = KColumn(String(10), nullable = True)
    legl_jijc_legl_dong_cd = KColumn(String(10), nullable = True)
    use_yn = KColumn(String(1), nullable = True)


    def __init__(self, *args, **kwargs):
        KTable.__init__(self)
        self.legl_dong_cd =  kwargs.pop('legl_dong_cd')
        self.legl_dong_nm =  kwargs.pop('legl_dong_nm',None)
        self.legl_dong_whl_nm =  kwargs.pop('legl_dong_whl_nm',None)
        self.up_legl_dong_cd =  kwargs.pop('up_legl_dong_cd',None)
        self.lv_cd =  kwargs.pop('lv_cd',None)
        self.sort_seq =  kwargs.pop('sort_seq',None)
        self.reg_ymd =  kwargs.pop('reg_ymd',None)
        self.clos_ymd =  kwargs.pop('clos_ymd',None)
        self.finl_job_ymd =  kwargs.pop('finl_job_ymd',None)
        self.rsdt_legl_dong_cd =  kwargs.pop('rsdt_legl_dong_cd',None)
        self.legl_jijc_legl_dong_cd =  kwargs.pop('legl_jijc_legl_dong_cd',None)
        self.use_yn =  kwargs.pop('use_yn','Y')

    def __repr__(self):
        return "<LeglDong('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s'" % (str(self.legl_dong_cd), str(self.legl_dong_nm), str(self.legl_dong_whl_nm), str(self.up_legl_dong_cd), str(self.lv_cd), str(self.sort_seq), str(self.reg_ymd), str(self.clos_ymd), str(self.finl_job_ymd), str(self.rsdt_legl_dong_cd), str(self.legl_jijc_legl_dong_cd), str(self.use_yn) + KTable.__repr__(self))

class NvCmpx(Base,KTable):
    __tablename__ = 'kred_nv_cmpx'

    nv_cmpx_id = KColumn(String(6), primary_key = True, nullable = False)
    nv_cmpx_nm = KColumn(String(100), nullable = True)
    legl_dong_cd = KColumn(String(10), nullable = False)
    nv_cmpx_knd = KColumn(String(20), nullable = True)
    bas_addr = KColumn(String(255), nullable = True)
    dtl_addr = KColumn(String(255), nullable = True)
    road_nm_bas_addr = KColumn(String(255), nullable = True)
    road_nm_dtl_addr = KColumn(String(255), nullable = True)
    addr = KColumn(String(255), nullable = True)
    x_coor_val = KColumn(FLOAT, nullable = True)
    y_coor_val = KColumn(FLOAT, nullable = True)
    tot_hshl_cnt = KColumn(Integer, nullable = True)
    tot_rent_hshl_cnt = KColumn(Integer, nullable = True)
    tot_dong_cnt = KColumn(Integer, nullable = True)
    max_flr = KColumn(Integer, nullable = True)
    min_flr = KColumn(Integer, nullable = True)
    cmpl_yymm = KColumn(String(8), nullable = True)
    sale_cnt = KColumn(String(50), nullable = True)
    js_cnt = KColumn(Integer, nullable = True)
    ws_cnt = KColumn(Integer, nullable = True)
    shrt_rent_cnt = KColumn(Integer, nullable = True)
    bld_co_nm = KColumn(String(200), nullable = True)
    tot_park_cnt = KColumn(Integer, nullable = True)
    hshl_per_park_cnt = KColumn(Integer, nullable = True)
    heat_way = KColumn(String(1000), nullable = True)
    heat_fuel = KColumn(String(1000), nullable = True)
    far = KColumn(String(1000), nullable = True)
    btlr = KColumn(String(1000), nullable = True)
    mbig_sply_area = KColumn(Float, nullable = True)
    msml_sply_area = KColumn(Float, nullable = True)
    cmpx_reg_val = KColumn(String(200), nullable = True)
    area_lst = KColumn(String(1000), nullable = True)
    mgmt_co_tel = KColumn(String(30), nullable = True)
    sbwy_info = KColumn(String(1000), nullable = True)
    wasp_pipe_rplc = KColumn(String(200), nullable = True)
    whl_dong_cnt = KColumn(Integer, nullable = True)
    bmak_yn = KColumn(String(1), nullable = True)
    mig_rsn = KColumn(String(20), nullable = True)

    legldong = relationship('LeglDong',primaryjoin = legl_dong_cd==LeglDong.legl_dong_cd, foreign_keys = [LeglDong.legl_dong_cd], passive_deletes = True)

    def __init__(self, *args, **kwargs):
        KTable.__init__(self)
        self.nv_cmpx_id =  kwargs.pop('nv_cmpx_id')
        self.nv_cmpx_nm =  kwargs.pop('nv_cmpx_nm',None)
        self.legl_dong_cd =  kwargs.pop('legl_dong_cd')
        self.nv_cmpx_knd =  kwargs.pop('nv_cmpx_knd',None)
        self.bas_addr =  kwargs.pop('bas_addr',None)
        self.dtl_addr =  kwargs.pop('dtl_addr',None)
        self.road_nm_bas_addr =  kwargs.pop('road_nm_bas_addr',None)
        self.road_nm_dtl_addr =  kwargs.pop('road_nm_dtl_addr',None)
        self.addr =  kwargs.pop('addr',None)
        self.x_coor_val =  kwargs.pop('x_coor_val',None)
        self.y_coor_val =  kwargs.pop('y_coor_val',None)
        self.tot_hshl_cnt =  kwargs.pop('tot_hshl_cnt',None)
        self.tot_rent_hshl_cnt =  kwargs.pop('tot_rent_hshl_cnt',None)
        self.tot_dong_cnt =  kwargs.pop('tot_dong_cnt',None)
        self.max_flr =  kwargs.pop('max_flr',None)
        self.min_flr =  kwargs.pop('min_flr',None)
        self.cmpl_yymm =  kwargs.pop('cmpl_yymm',None)
        self.sale_cnt =  kwargs.pop('sale_cnt',None)
        self.js_cnt =  kwargs.pop('js_cnt',None)
        self.ws_cnt =  kwargs.pop('ws_cnt',None)
        self.shrt_rent_cnt =  kwargs.pop('shrt_rent_cnt',None)
        self.bld_co_nm =  kwargs.pop('bld_co_nm',None)
        self.tot_park_cnt =  kwargs.pop('tot_park_cnt',None)
        self.hshl_per_park_cnt =  kwargs.pop('hshl_per_park_cnt',None)
        self.heat_way =  kwargs.pop('heat_way',None)
        self.heat_fuel =  kwargs.pop('heat_fuel',None)
        self.far =  kwargs.pop('far',None)
        self.btlr =  kwargs.pop('btlr',None)
        self.mbig_sply_area =  kwargs.pop('mbig_sply_area',None)
        self.msml_sply_area =  kwargs.pop('msml_sply_area',None)
        self.cmpx_reg_val =  kwargs.pop('cmpx_reg_val',None)
        self.area_lst =  kwargs.pop('area_lst',None)
        self.mgmt_co_tel =  kwargs.pop('mgmt_co_tel',None)
        self.sbwy_info =  kwargs.pop('sbwy_info',None)
        self.wasp_pipe_rplc =  kwargs.pop('wasp_pipe_rplc',None)
        self.whl_dong_cnt =  kwargs.pop('whl_dong_cnt',None)
        self.bmak_yn =  kwargs.pop('bmak_yn',None)
        self.mig_rsn =  kwargs.pop('mig_rsn',None)

    def __repr__(self):
        return "<NvCmpx('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s'" % (str(self.nv_cmpx_id), str(self.nv_cmpx_nm), str(self.legl_dong_cd), str(self.nv_cmpx_knd), str(self.bas_addr), str(self.dtl_addr), str(self.road_nm_bas_addr), str(self.road_nm_dtl_addr), str(self.addr), str(self.x_coor_val), str(self.y_coor_val), str(self.tot_hshl_cnt), str(self.tot_rent_hshl_cnt), str(self.tot_dong_cnt), str(self.max_flr), str(self.min_flr), str(self.cmpl_yymm), str(self.sale_cnt), str(self.js_cnt), str(self.ws_cnt), str(self.shrt_rent_cnt), str(self.bld_co_nm), str(self.tot_park_cnt), str(self.hshl_per_park_cnt), str(self.heat_way), str(self.heat_fuel), str(self.far), str(self.btlr), str(self.mbig_sply_area), str(self.msml_sply_area), str(self.cmpx_reg_val), str(self.area_lst), str(self.mgmt_co_tel), str(self.sbwy_info), str(self.wasp_pipe_rplc), str(self.whl_dong_cnt), str(self.bmak_yn), str(self.mig_rsn) + KTable.__repr__(self))

class NvCmpxTyp(Base,KTable):
    __tablename__ = 'kred_nv_cmpx_typ'

    nv_cmpx_id = KColumn(String(6), primary_key = True, nullable = False)
    nv_cmpx_typ_seq = KColumn(Integer, primary_key = True, nullable = False)
    cmpx_typ_nm = KColumn(String(200), nullable = True)
    sply_area = KColumn(FLOAT, nullable = True)
    only_area = KColumn(FLOAT, nullable = True)
    only_pyng_nm = KColumn(String(200), nullable = True)
    cmpx_typ_pyng_nm = KColumn(String(200), nullable = True)
    gpln_cors = KColumn(String(1000), nullable = True)
    door_strc = KColumn(String(200), nullable = True)
    room_cnt_str = KColumn(String(200), nullable = True)
    bath_cnt_str = KColumn(String(200), nullable = True)
    soh_hshl_cnt = KColumn(Integer, nullable = True)
    sply_area_num = KColumn(Float, nullable = True)
    only_area_num = KColumn(Float, nullable = True)
    ret_typ_cd = KColumn(String(20), nullable = True, kcom_cd_domain = True, kcom_cd_grp = '')
    avg_mntn_amt = KColumn(Integer, nullable = True)
    smmr_mntn_amt = KColumn(Integer, nullable = True)
    wntr_mntn_amt = KColumn(Integer, nullable = True)
    deal_lmit_ymd = KColumn(String(8), nullable = True)
    deal_psbl_ymd = KColumn(String(8), nullable = True)
    dcnt_prc_str = KColumn(String(200), nullable = True)

    nvcmpx = relationship('NvCmpx',primaryjoin = nv_cmpx_id==NvCmpx.nv_cmpx_id, foreign_keys = [NvCmpx.nv_cmpx_id], passive_deletes = True)

    def __init__(self, *args, **kwargs):
        KTable.__init__(self)
        self.nv_cmpx_id =  kwargs.pop('nv_cmpx_id')
        self.nv_cmpx_typ_seq =  kwargs.pop('nv_cmpx_typ_seq')
        self.cmpx_typ_nm =  kwargs.pop('cmpx_typ_nm',None)
        self.sply_area =  kwargs.pop('sply_area',None)
        self.only_area =  kwargs.pop('only_area',None)
        self.only_pyng_nm =  kwargs.pop('only_pyng_nm',None)
        self.cmpx_typ_pyng_nm =  kwargs.pop('cmpx_typ_pyng_nm',None)
        self.gpln_cors =  kwargs.pop('gpln_cors',None)
        self.door_strc =  kwargs.pop('door_strc',None)
        self.room_cnt_str =  kwargs.pop('room_cnt_str',None)
        self.bath_cnt_str =  kwargs.pop('bath_cnt_str',None)
        self.soh_hshl_cnt =  kwargs.pop('soh_hshl_cnt',None)
        self.sply_area_num =  kwargs.pop('sply_area_num',None)
        self.only_area_num =  kwargs.pop('only_area_num',None)
        self.ret_typ_cd =  kwargs.pop('ret_typ_cd',None)
        self.avg_mntn_amt =  kwargs.pop('avg_mntn_amt',None)
        self.smmr_mntn_amt =  kwargs.pop('smmr_mntn_amt',None)
        self.wntr_mntn_amt =  kwargs.pop('wntr_mntn_amt',None)
        self.deal_lmit_ymd =  kwargs.pop('deal_lmit_ymd',None)
        self.deal_psbl_ymd =  kwargs.pop('deal_psbl_ymd',None)
        self.dcnt_prc_str =  kwargs.pop('dcnt_prc_str',None)

    def __repr__(self):
        return "<NvCmpxTyp('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s'" % (str(self.nv_cmpx_id), str(self.nv_cmpx_typ_seq), str(self.cmpx_typ_nm), str(self.sply_area), str(self.only_area), str(self.only_pyng_nm), str(self.cmpx_typ_pyng_nm), str(self.gpln_cors), str(self.door_strc), str(self.room_cnt_str), str(self.bath_cnt_str), str(self.soh_hshl_cnt), str(self.sply_area_num), str(self.only_area_num), str(self.ret_typ_cd), str(self.avg_mntn_amt), str(self.smmr_mntn_amt), str(self.wntr_mntn_amt), str(self.deal_lmit_ymd), str(self.deal_psbl_ymd), str(self.dcnt_prc_str) + KTable.__repr__(self))

