/* 테이블명 변경 */
alter table atcl_sop rename atcl_sop_bak;

alter table kmig_kb_prc_stat MODIFY column 10Y_GAP_ROR FLOAT(10,2);
/* 컬럼명 변경 */
ALTER TABLE kmig_kb_cmpx_typ_mon_prc CHANGE GNRL_GAP GNRL_GAP_PRC DECIMAL(10,0);
ALTER TABLE KADM_COM_CD_LST CHANGE DEL_YN DEL_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE KADM_COM_CD_DTL CHANGE EFF_OPEN_YMD EFF_STA_YMD VARCHAR(8);
ALTER TABLE KADM_SVC_PASI_ITEM ADD COLUMN EXCP_STR VARCHAR(200) NULL;
ALTER TABLE atcl_sop MODIFY COLUMN PRBL_JOB_NUM VARCHAR(50) NOT NULL DEFAULT('Y') COMMENT '사용여부'; #AFTER ITEM_VAL;
ALTER TABLE atcl_sop MODIFY COLUMN PRBL_JOB_NUM VARCHAR(50); #AFTER ITEM_VAL;
ALTER TABLE kadm_Svc DROP COLUMN PARM_LOAD_FUNC_NM;
ALTER TABLE kadm_svc_pasi_item MODIFY EFF_STA_YMD VARCHAR(8) NOT NULL DEFAULT('99991231');
ALTER TABLE KADM_SITE MODIFY SLEP_SEC DECIMAL(10,1);
/* 컬럼순서 변경 */ ALTER TABLE kadm_svc_pasi_item MODIFY COLUMN excp_str VARCHAR(200) NULL COMMENT '제외문자열' AFTER col_nm;
#ITEM_SRC_CL_CD
UPDATE 
#SELECT * FROM 
KADM_SVC_PASI_ITEM
#where com_cd_grp like '%WAY%'
SET ITEM_SRC_CL_CD = 'NA'
#WHERE EFF_END_YMD IS NULL
;
SELECT * FROM ATCL_LOG
;
/* INDEX 추가*/
ALTER TABLE ATCL_LOG ADD INDEX(ERR_OCCR_DT,LOGIN_ID);
ALTER TABLE ATCL_LOG ADD INDEX(keyword(20));
/* INDEX DROP */
ALTER TABLE KMIG_KB_PRC_STAT DROP INDEX 1M_RISE_PRC_2;
/* DEFAULT 추가 */
alter table kadm_tlgr_user add column seq decimal(10,0) default 100

;
desc kadm_svc
;
-- KB시세통계
ALTER TABLE `rep`.`KMIG_KB_PRC_STAT`
	ADD CONSTRAINT `PK_KMIG_KB_PRC_STAT` -- KB시세통계 기본키
		PRIMARY KEY (
			`CMPX_IDF_ID`,   -- 물건식별자ID
			`HOUSE_TYP_SEQ`, -- 주택형일련번호
			`STD_YYMM`       -- 기준년월
		);
#1M_RISE_PRC
#1M_ROR
#10Y_GAP_ROR
;
select * from kadm_job_act_exec
;
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_RISE_PRC);
;
drop table kadm_svc_parm
;


ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(6M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(2Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(4Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(5Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(10Y_RISE_PRC);

ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(6M_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(2Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(4Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(5Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(10Y_ROR);

ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(6M_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(2Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(4Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(5Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(10Y_GAP_ROR);





ALTER TABLE KMIG_KB_PRC_STAT DROP INDEX 1M_RISE_PRC_2;


ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);

ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(keyword(20));
        
        
        
        
        