alter table kmig_kb_prc_stat MODIFY column 10Y_GAP_ROR FLOAT(10,2)
;
/* 컬럼명 변경 */
ALTER TABLE kmig_kb_cmpx_typ_mon_prc CHANGE GNRL_GAP GNRL_GAP_PRC DECIMAL(10,0)
;
;
/* INDEX 추가*/
ALTER TABLE temp ADD INDEX(keyword(20));
/* INDEX DROP */
ALTER TABLE KMIG_KB_PRC_STAT DROP INDEX 1M_RISE_PRC_2;
/* DEFAULT 추가 */
alter table kadm_tlgr_user add column seq decimal(10,0) default 100

;
-- KB시세통계
ALTER TABLE `rep`.`KMIG_KB_PRC_STAT`
	ADD CONSTRAINT `PK_KMIG_KB_PRC_STAT` -- KB시세통계 기본키
		PRIMARY KEY (
			`CMPX_IDF_ID`,   -- 물건식별자ID
			`HOUSE_TYP_SEQ`, -- 주택형일련번호
			`STD_YYMM`       -- 기준년월
		);
#1M_RISE_PRC
#1M_ROR
#10Y_GAP_ROR
;
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_RISE_PRC);
;


ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(6M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(2Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(4Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(5Y_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(10Y_RISE_PRC);

ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(6M_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(2Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(4Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(5Y_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(10Y_ROR);

ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1M_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(6M_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(1Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(2Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(4Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(5Y_GAP_ROR);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(10Y_GAP_ROR);





ALTER TABLE KMIG_KB_PRC_STAT DROP INDEX 1M_RISE_PRC_2;


ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);

ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(3M_RISE_PRC);
ALTER TABLE KMIG_KB_PRC_STAT ADD INDEX(keyword(20));
        
        
        
        
        