#LV1 시/도 MIG
INSERT INTO KRED_LEGL_REGN
SELECT KSCC_BIG_CL_CD LEGL_REGN_CD
     , KSCC_SIDO_NM LEGL_REGN_NM
     , KSCC_ENGL_MARK LEGL_REGN_ENGL
     , NULL UP_LEGL_REGN_CD
     , '1' LV_CD
     , 1000000001 REG_USER_ID
     , NOW() REG_DTM
     , 1000000001 CHG_USER_ID
     , NOW() CHG_DTM
FROM kmig_kscc_legl_dong
WHERE KSCC_MID_CL_CD = ''
AND LENGTH(KSCC_BIG_CL_CD) > 1
;
#LV2 구가 존재하는 시 MIG
INSERT INTO KRED_LEGL_REGN
SELECT KSCC_MID_CL_CD LEGL_REGN_CD
     , KSCC_SGG_NM LEGL_REGN_NM
     , KSCC_ENGL_MARK LEGL_REGN_ENGL
     , KSCC_BIG_CL_CD UP_LEGL_REGN_CD
     , '2' LV_CD
     , 1000000001 REG_USER_ID
     , NOW() REG_DTM
     , 1000000001 CHG_USER_ID
     , NOW() CHG_DTM
FROM kmig_kscc_legl_dong
GROUP BY KSCC_MID_CL_CD
HAVING COUNT(*) = 1
;
#LV3 (시/군/구) MIG
INSERT INTO KRED_LEGL_REGN
SELECT KSCC_MID_CL_CD LEGL_REGN_CD
     , KSCC_SGG_NM LEGL_REGN_NM
     , KSCC_ENGL_MARK LEGL_REGN_ENGL
     , KSCC_BIG_CL_CD UP_LEGL_REGN_CD
     , '3' LV_CD
     , 1000000001 REG_USER_ID
     , NOW() REG_DTM
     , 1000000001 CHG_USER_ID
     , NOW() CHG_DTM
FROM kmig_kscc_legl_dong
WHERE KSCC_SMALL_CL_CD = ''
AND LENGTH(KSCC_MID_CL_CD) > 1
AND KSCC_MID_CL_CD NOT IN ( 
	SELECT LEGL_REGN_CD 
    FROM KRED_LEGL_REGN
)    
;
#시가 존재하는 구에대해 상위 지역코드 MIG
UPDATE 
#SELECT * FROM 
KRED_LEGL_REGN
SET UP_LEGL_REGN_CD = CONCAT(substring(LEGL_REGN_CD,1,4),"0")
WHERE LV_CD = '3'
AND substring(LEGL_REGN_CD,5,1) != '0'
;
#LV2가 존재하는 리스트 조회
SELECT *
FROM KRED_LEGL_REGN KLR1
INNER JOIN KRED_LEGL_REGN KLR2
ON KLR1.LEGL_REGN_CD = KLR2.UP_LEGL_REGN_CD
WHERE KLR1.LV_CD = '2'
;
#LV4 (읍/면/동)MIG
INSERT INTO KRED_LEGL_REGN
SELECT KSCC_SMALL_CL_CD LEGL_REGN_CD
     , KSCC_EMD_NM LEGL_REGN_NM
     , KSCC_ENGL_MARK LEGL_REGN_ENGL
     , KSCC_MID_CL_CD UP_LEGL_REGN_CD
     , '4' LV_CD
     , 1000000001 REG_USER_ID
     , NOW() REG_DTM
     , 1000000001 CHG_USER_ID
     , NOW() CHG_DTM
FROM kmig_kscc_legl_dong
WHERE 1=1
AND LENGTH(KSCC_SMALL_CL_CD) > 1
;
/* DATA 검증 */
#229
SELECT COUNT(*) FROM KMIG_KB_REGN
WHERE LV_CD = '2'
;
#250
SELECT COUNT(*) FROM KRED_LEGL_REGN
WHERE LV_CD = '3'
;
#KB와 시/군/구 비교 -> 구가 있는 시에서 차이남 + 세종시
SELECT *
FROM KMIG_KB_REGN KR
LEFT JOIN KRED_LEGL_REGN LR
ON KR.KB_REGN_NM = LR.LEGL_REGN_NM
AND LR.LV_CD = '3'
WHERE KR.LV_CD = '2'
AND LR.LEGL_REGN_CD IS NULL
;
#KB와 시/군/구 비교 -> 구가 있는 시에서 차이남 + 세종시
SELECT *
FROM KRED_LEGL_REGN LR
LEFT JOIN  KMIG_KB_REGN KR
ON KR.KB_REGN_NM = LR.LEGL_REGN_NM
AND KR.LV_CD = '2'
WHERE LR.LV_CD = '3'
AND KR.KB_REGN_CD IS NULL
;
#4724
SELECT COUNT(*) FROM KMIG_KB_REGN
WHERE LV_CD = '3'
;
#3498
SELECT COUNT(*) FROM KRED_LEGL_REGN
WHERE LV_CD = '4'
;
SELECT *
FROM KMIG_KB_REGN KR
LEFT JOIN KRED_LEGL_REGN LR
ON KR.KB_REGN_NM = LR.LEGL_REGN_NM
AND LR.LV_CD = '4'
WHERE KR.LV_CD = '3'
AND LR.LEGL_REGN_CD IS NULL
;


