SELECT * 
FROM KADM_JOB J
INNER JOIN KADM_JOB_ACT JA
ON J.JOB_ID = JA.JOB_ID
INNER JOIN KADM_ACT A
ON JA.ACT_ID = A.ACT_ID
INNER JOIN KADM_ACT_FUNC AF
ON A.ACT_ID = AF.ACT_ID
INNER JOIN KADM_FUNC F
ON AF.FUNC_ID = F.FUNC_ID
WHERE 1=1
AND J.JOB_ID = 'NVIN001'
;
SELECT * FROM KADM_JOB
INS_NV_CMPX
;


SELECT * FROM KADM_COM_CD_DTL
;


