SELECT A.CMPX_IDF_ID
     , A.CMPX_IDF_NM
     , A.GOV_LEGL_DONG_CD
     , SUBSTRING(GOV_LEGL_DONG_CD,1,5)||'00000'
     , A.TOT_HSHL_CNT
     , A.CMPL_YYMM
     , A.GOV_LEGL_DONG_NM
     , A.HOUSE_TYP_NM
     , A.PYNG_PER_SALE_PRC
     , A.PYNG_PER_JS_PRC
     , ROUND(A.PYNG_PER_JS_PRC/A.PYNG_PER_SALE_PRC*100,0)
     , A.SALES_RANK
FROM (
	SELECT *
		, RANK() OVER (
			partition by SUBSTRING(GOV_LEGL_DONG_CD,1,5)
			ORDER BY PYNG_PER_SALE_PRC DESC
		)	SALES_RANK
	FROM kmig_kb_cmpx_typ_now_prc_stat
	WHERE KB_CMPX_KND = '아파트'
	AND CMPL_YYMM > '199000'
    AND SPLY_AREA BETWEEN 100 AND 130
)    A 
WHERE A.SALES_RANK = 1
ORDER BY PYNG_PER_SALE_PRC DESC
;
UPDATE kmig_kb_cmpx_typ_now_prc_stat
SET PYNG_PER_SALE_PRC = GNRL_AVG_PRC/SPLY_AREA*3.3
  , PYNG_PER_JS_PRC = GNRL_JS_AVG_PRC/SPLY_AREA*3.3
;

SELECT LD.LEGL_DONG_CD
     , LD.LEGL_DONG_NM
     , REP_APT.CMPX_IDF_ID
     , REP_APT.CMPX_IDF_NM
     , REP_APT.TOT_HSHL_CNT
     , REP_APT.CMPL_YYMM
     , REP_APT.HOUSE_TYP_NM
     , REP_APT.PYNG_PER_SALE_PRC
     , REP_APT.PYNG_PER_JS_PRC
     , REP_APT.JS_PER_RATE
	 , REP_APT.GNRL_AVG_PRC
	 , REP_APT.GNRL_JS_AVG_PRC
FROM KRED_LEGL_DONG LD
LEFT OUTER JOIN 
(
	SELECT A.CMPX_IDF_ID
		 , A.CMPX_IDF_NM
		 , A.GOV_LEGL_DONG_CD
         , CONCAT(SUBSTRING(A.GOV_LEGL_DONG_CD,1,5),'00000') LV2_LEGL_DONG_CD
		 , A.TOT_HSHL_CNT
		 , A.CMPL_YYMM
		 , A.GOV_LEGL_DONG_NM
		 , A.HOUSE_TYP_NM
		 , A.PYNG_PER_SALE_PRC
		 , A.PYNG_PER_JS_PRC
		 , ROUND(A.PYNG_PER_JS_PRC/A.PYNG_PER_SALE_PRC*100,0) JS_PER_RATE
		 , A.SALES_RANK
         , A.GNRL_AVG_PRC
         , A.GNRL_JS_AVG_PRC
	FROM (
		SELECT *
			, RANK() OVER (
				partition by SUBSTRING(GOV_LEGL_DONG_CD,1,5)
				ORDER BY PYNG_PER_SALE_PRC DESC
			)	SALES_RANK
		FROM kmig_kb_cmpx_typ_now_prc_stat
		WHERE KB_CMPX_KND = '아파트'
		AND CMPL_YYMM > '199000'
		AND SPLY_AREA BETWEEN 100 AND 130
	)    A 
	WHERE A.SALES_RANK = 1
) REP_APT
ON LD.LEGL_DONG_CD = REP_APT.LV2_LEGL_DONG_CD
WHERE NOT EXISTS (
	SELECT 1
    FROM KRED_LEGL_DONG LD2
    WHERE LD2.LV_CD = '2'
    AND LD.LEGL_DONG_CD = LD2.UP_LEGL_DONG_CD
) #성남시 용인시등 LV2에 시와 구가 같이 있는 경우 시를 제외 한다.
AND LD.LV_CD = '2'
AND (LD.LEGL_DONG_CD LIKE '11%' OR LD.LEGL_DONG_CD LIKE '41%')
ORDER BY PYNG_PER_SALE_PRC DESC 
;
SELECT * FROM kmig_kb_cmpx_typ_now_prc_stat