#SQL문장을 직접 정의하는 파일
redSqlDic = {
    'selectLeglLv3Dong':"SELECT LEGL_DONG_CD FROM KRED_LEGL_DONG WHERE LV_CD = '3' ORDER BY LEGL_DONG_CD ASC",
    'selectCmpxIdAll':"SELECT NV_CMPX_ID FROM KMIG_NV_CMPX ORDER BY NV_CMPX_ID ASC"
}
