#SQL문장을 직접 정의하는 파일
redSqlDic = {
    'selectLeglLv3Dong':"SELECT LEGL_DONG_CD FROM KRED_LEGL_DONG WHERE LV_CD = '3' ORDER BY LEGL_DONG_CD ASC",
    'selectCmpxIdAll':"SELECT NV_CMPX_ID FROM KMIG_NV_CMPX WHERE NV_CMPX_ID ORDER BY NV_CMPX_ID ASC",
    'selectLeglLv2Dong': "SELECT SUBSTR(LEGL_DONG_CD, 1, 5) AS LEGL_DONG_CD FROM KRED_LEGL_DONG WHERE LV_CD = '2' AND LEGL_DONG_CD >= '44800' ORDER BY LEGL_DONG_CD ASC",
    'selectYYMM': "SELECT STD_YYMM FROM KADM_STD_YYMM WHERE STD_YYMM BETWEEN '200601' AND DATE_FORMAT(NOW(), '%Y%m%d')",
    'selectOmitLeglLv2Dong': "SELECT STD_YYMM, SUBSTR(LD.LEGL_DONG_CD,1,5) AS LEGL_DONG_CD FROM KADM_STD_YYMM SY, KRED_LEGL_DONG LD "\
                             "WHERE SY.STD_YYMM BETWEEN '200601' AND DATE_FORMAT(NOW(), '%Y%m%d') AND LD.LV_CD = '2' "\
                             "AND NOT EXISTS (SELECT 1 FROM kmig_deal_dtl DD WHERE DD.DEAL_YYMM = SY.STD_YYMM AND SUBSTR(LD.LEGL_DONG_CD,1,5) = DD.GOV_LEGL_DONG_CD)",
    'selectDupLeglLv2Dong' : "SELECT TMP_CD AS LEGL_DONG_CD FROM KADM_TMP_CD_DTL WHERE TMP_CD_GRP = 'DUP' AND TMP_CD >= '41480'",
    'selectJobSchdUsingAll' : "SELECT JOB_ID,JOB_SEQ,EXEC_PERD_CD,EXEC_MM,EXEC_DD,EXEC_HH,EXEC_MI,EXEC_DAY_CD,CYCL_MI FROM KADM_JOB_SCHD WHERE USE_YN = 'Y' AND DEL_YN = 'N'",
    'selectJobSchdImdi' : "SELECT JOB_ID,JOB_SEQ,EXEC_PERD_CD,EXEC_MM,EXEC_DD,EXEC_HH,EXEC_MI,EXEC_DAY_CD,CYCL_MI FROM KADM_JOB_SCHD WHERE IMDI_EXEC_YN = 'Y' AND USE_YN = 'Y' AND DEL_YN = 'N'"
}
