dicMappNaverComplexList = {
    'complexNo': 'NV_CMPX_ID',
    'complexName': 'NV_CMPX_NM',
    'cortarNo': 'GOV_LEGL_DONG_CD',
    'realEstateTypeCode': 'NV_CMPX_KND',
    'cortarAddress': 'BAS_ADDR',
    'detailAddress': 'DTL_ADDR',
    'latitude': 'X_COOR_VAL',
    'longitude': 'Y_COOR_VAL',
    'totalHouseholdCount': 'TOT_HSHL_CNT',
    'totalBuildingCount': 'TOT_DONG_CNT',
    'highFloor': 'MAX_FLR',
    'lowFloor': 'MIN_FLR',
    'completionYearMonth': 'CMPL_YYMM',
    'dealCount': 'SALE_CNT',
    'leaseCount': 'JS_CNT',
    'rentCount': 'WS_CNT',
    'shortTermRentCount': 'SHRT_RENT_CNT',
}