/*거래가격컬럼 숫자 변환*/
UPDATE KMIG_NV_CMPX_ATCL_BAK
SET DEAL_PRC_NUM = CONCAT(SUBSTRING_INDEX(REPLACE(REPLACE(DEAL_PRC_NM,' ',''),',',''),'억',1),LPAD(SUBSTRING_INDEX(REPLACE(REPLACE(DEAL_PRC_NM,' ',''),',',''),'억',-1),4,'0'))
WHERE DEAL_PRC_NM LIKE '%억%'
#AND LENGTH(DEAL_PRC_NM) < 7
;
UPDATE KMIG_NV_CMPX_ATCL_BAK
SET DEAL_PRC_NUM = REPLACE(REPLACE(DEAL_PRC_NM,' ',''),',','')
WHERE DEAL_PRC_NM NOT LIKE '%억%'
;
/*+ 전체건수 */
SELECT COUNT(*) #566269
FROM KMIG_NV_CMPX_ATCL_BAK
;
/* 억 */
SELECT COUNT(*) #483877
FROM KMIG_NV_CMPX_ATCL_BAK
WHERE DEAL_PRC_NM LIKE '%억%'
;
