/* 단지별 매물 갯수 검증 */
SELECT NC.NV_CMPX_ID, NC.NV_CMPX_NM, NC.TOT_HSHL_CNT, BAK.CNT, NOW.CNT
FROM KMIG_NV_CMPX NC
LEFT OUTER JOIN (
	SELECT NCAB.NV_CMPX_ID, COUNT(*) CNT
	FROM KMIG_NV_CMPX_ATCL_BAK NCAB
	GROUP BY NCAB.NV_CMPX_ID
) BAK
ON BAK.NV_CMPX_ID = NC.NV_CMPX_ID
LEFT OUTER JOIN (
	SELECT NCA.NV_CMPX_ID, COUNT(*) CNT
	FROM KMIG_NV_CMPX_ATCL NCA
	GROUP BY NCA.NV_CMPX_ID
) NOW
ON NOW.NV_CMPX_ID = NC.NV_CMPX_ID
WHERE 1=1
AND BAK.CNT > 10
AND NOW.CNT IS NULL
AND NC.NV_CMPX_ID < '13071'
ORDER BY NC.NV_CMPX_ID
#ORDER BY NC.TOT_HSHL_CNT DESC
;
/* 매물 없는 단지중 대단지 ORDER BY */
SELECT NC.TOT_HSHL_CNT, NC.*
FROM KMIG_NV_CMPX NC
WHERE NC.NV_CMPX_ID < (SELECT MAX(NV_CMPX_ID) FROM KMIG_NV_CMPX_ATCL)
AND NOT EXISTS (
	SELECT 1
    FROM KMIG_NV_CMPX_ATCL NCA
    WHERE NCA.NV_CMPX_ID = NC.NV_CMPX_ID
)
ORDER BY NC.TOT_HSHL_CNT DESC
;

;
SELECT MAX(NV_CMPX_ID) FROM KMIG_NV_CMPX_ATCL
;
/*delete from 
kmig_nv_cmpx_atcl
where nv_cmpx_id = '114655'*/
;
SELECT * fROM KMIG_NV_CMPX
WHERE NV_CMPX_ID = '114655'
;

SELECT * 
FROM KMIG_NV_CMPX_ATCL_BAK NCAB
INNER JOIN KMIG_NV_CMPX NC
ON NCAB.NV_CMPX_ID = NC.NV_CMPX_ID
AND NC.GOV_LEGL_DONG_CD LIKE '11%'
WHERE NV_DEAL_TYP_cD = 'B1'
ORDER BY DEAL_PRC_NUM ASC
;
SELECT COUNT(*) FROM KMIG_NV_CMPX_ATCL
;
SELECT COUNT(*) FROM KMIG_NV_CMPX_ATCL_BAK
;

SELECT NCAB.ATCL_NUM, NCAB.DTL_ADDR, NCAB.ATCL_CHK_YMD, NCAB.NV_DEAL_TYP_CD, NCAB.FLR_INFO, NCAB.NV_CMPX_TYP_SEQ, NC.*, NCAB.*
FROM KMIG_NV_CMPX_ATCL_BAK NCAB
LEFT OUTER JOIN KMIG_NV_CMPX_ATCL NCA
ON NCAB.ATCL_NUM = NCA.ATCL_NUM
INNER JOIN KMIG_NV_CMPX NC
ON NCAB.NV_CMPX_ID = NC.NV_CMPX_ID
WHERE NCA.ATCL_NUM IS NULL
ORDER BY NC.NV_CMPX_ID ASC
;

SELECT NC.NV_CMPX_ID, NC.NV_CMPX_NM, NCA.NV_DEAL_TYP_CD, COUNT(*)
FROM KMIG_NV_CMPX_ATCL NCA
INNER JOIN KMIG_NV_CMPX NC 
ON NCA.NV_CMPX_ID = NC.NV_CMPX_ID
GROUP BY NCA.NV_CMPX_ID, NCA.NV_CMPX_NM, NCA.NV_DEAL_TYP_CD
ORDER BY NC.NV_CMPX_ID, NCA.NV_DEAL_TYP_CD
;
SELECT ATCL_NUM, COUNT(*)
FROM KMIG_NV_CMPX_ATCL_BAK
GROUP BY ATCL_NUM
HAVING COUNT(*) > 1
;

select * from kmig_nv_cmpx
where nv_cmpx_id = '101013'



;
SELECT COUNT(*) FROM KMIG_NV_CMPX_ATCL
;
delete FROM KMIG_NV_CMPX_ATCL;
delete FROM KMIG_NV_CMPX_ATCL_TAG;
SELECT * FROM KMIG_NV_CMPX_ATCL_BAK
WHERE NV_CMPX_ID = '100040'

;
delete from KMIG_NV_CMPX_ATCL
;
delete from kmig_nv_cmpx_atcl_tag
;

truncate table kmig_nv_cmpx_atcl_tag
;

SELECT * FROM KMIG_NV_CMPX
WHERE NV_CMPX_ID = '118830'
;