#잘못됨 
INSERT INTO KRED_LEGL_DONG
SELECT GOV_LEGL_DONG_CD       LEGL_DONG_CD
     , LWST_REGN_NM           LEGL_DONG_NM
     , GOV_LEGL_DONG_NM       LEGL_DONG_WHL_NM
     , NULL UP_LEGL_DONG_CD
     , ROUND(LENGTH(REPLACE(GOV_LEGL_DONG_CD,'0',''))/2) LV_CD #¿À·ù
     , GRD
     , REG_YMD
     , CLOS_YMD
     , FINL_JOB_YMD
     , GOV_RSDT_LEGL_DONG_CD
     , LEGL_JIJC_LEGL_DONG_CD
     , (CASE WHEN clos_cl_Val = '현존' THEN 'Y' ELSE 'N' END) USE_YN
     , '1000000001'
     , NOW()
     , '1000000001'
     , NOW()
FROM KMIG_GOV_LEGL_DONG
WHERE clos_cl_Val = '현존'
;

#세종시 가상 최상위코드 마이그 
INSERT INTO KRED_LEGL_DONG
SELECT '3600000000' LEGL_DONG_CD
     , LEGL_DONG_NM
     , LEGL_DONG_WHL_NM
     , '0000000000' UP_LEGL_DONG_CD
     , '1' LV_CD
     , 16 SORT_SEQ
     , REG_YMD
     , CLOS_YMD
     , FINL_JOB_YMD
     , RSDT_LEGL_DONG_CD
     , LEGL_JIJC_LEGL_DONG_CD
     , 'Y'
     , 1000000001 REG_USER_ID
     , NOW() REG_DTM
     , 1000000001 CHG_USER_ID
     , NOW() CHG_DTM
FROM KRED_LEGL_DONG
WHERE LEGL_DONG_CD = '3611000000'
;

SELECT * FROM KRED_LEGL_DONG
WHERE LV_CD = '1'
;
/* 레벨2 마이그 */
#select RPAD(SUBSTRING(LEGL_DONG_CD,1,4),10,'0'), LV2.* FROM
update 
KRED_LEGL_DONG LV2
set LV2.LV_CD = 2
  , LV2.UP_LEGL_DONG_CD = RPAD(SUBSTRING(LV2.LEGL_DONG_CD,1,5),10,'0')
  , LV2.CHG_USER_ID = 9000000001
  , LV2.CHG_DTM = NOW()
WHERE substring(LV2.LEGL_DONG_CD,6,5) = '00000'
AND SUBSTRING(LV2.LEGL_DONG_CD,3,3) != '000'
AND LV2.LV_CD != 2
;
update
#select * from 
kred_legl_dong
set up_legl_dong_cd = RPAD(SUBSTRING(LEGL_DONG_CD,1,5),10,'0')
  , CHG_USER_ID = 9000000001
  , CHG_DTM = NOW()
where lv_cd = '2'
;
/* 레벨3 마이그 */
#select RPAD(SUBSTRING(LEGL_DONG_CD,1,4),10,'0'), LV3.* FROM
update 
KRED_LEGL_DONG LV3
set LV3.LV_CD = 3
  , LV3.UP_LEGL_DONG_CD = RPAD(SUBSTRING(LV3.LEGL_DONG_CD,1,5),10,'0')
  , LV3.CHG_USER_ID = 9000000001
  , LV3.CHG_DTM = NOW()
WHERE substring(LV3.LEGL_DONG_CD,9,2) = '00'
AND SUBSTRING(LV3.LEGL_DONG_CD,6,3) != '000'
AND LV3.LV_CD != 3
;
update
#select * from 
kred_legl_dong
set up_legl_dong_cd = RPAD(SUBSTRING(LEGL_DONG_CD,1,5),10,'0')
  , CHG_USER_ID = 9000000001
  , CHG_DTM = NOW()
where lv_cd = '3'
;

/* 레벨4 마이그 */
#select RPAD(SUBSTRING(LEGL_DONG_CD,1,8),10,'0'), LV3.* FROM
update 
KRED_LEGL_DONG LV3
set LV3.LV_CD = 4
  , LV3.UP_LEGL_DONG_CD = RPAD(SUBSTRING(LV3.LEGL_DONG_CD,1,8),10,'0')
  , LV3.CHG_USER_ID = 9000000001
  , LV3.CHG_DTM = NOW()
WHERE substring(LV3.LEGL_DONG_CD,9,2) != '00'
AND LV3.LV_CD != 4
;
update
#select * from 
kred_legl_dong
set up_legl_dong_cd = RPAD(SUBSTRING(LEGL_DONG_CD,1,8),10,'0')
  , CHG_USER_ID = 9000000001
  , CHG_DTM = NOW()
where lv_cd = '4'
;
#검증1 총건수 
SELECT COUNT(*) FROM KRED_LEGL_DONG #총건수 20542 > 20543(세종시 +1)
;
#검증2 
SELECT *
FROM KRED_LEGL_DONG
WHERE LV_CD NOT IN ('1','2','3','4')
;
#검증3
SELECT *
FROM KRED_LEGL_DONG LVN
LEFT OUTER JOIN KRED_LEGL_DONG UP_LV
ON LVN.UP_LEGL_DONG_CD = UP_LV.LEGL_DONG_CD
WHERE UP_LV.LEGL_DONG_CD IS NULL
ORDER BY LVN.LV_CD ASC
;