INSERT INTO KRED_LEGL_DONG
SELECT GOV_LEGL_DONG_CD
     , LWST_REGN_NM
     , GOV_LEGL_DONG_NM
     , NULL UP_LEGL_DONG_CD
     , ROUND(LENGTH(REPLACE(GOV_LEGL_DONG_CD,'0',''))/2) LV_CD
     , GRD
     , REG_YMD
     , CLOS_YMD
     , FINL_JOB_YMD
     , GOV_RSDT_LEGL_DONG_CD
     , LEGL_JIJC_LEGL_DONG_CD
     , '1000000001'
     , NOW()
     , '1000000001'
     , NOW()
FROM KMIG_GOV_LEGL_DONG
;
UPDATE KRED_LEGL_DONG
SET UP_LEGL_DONG_CD = RPAD(LEFT(LEGL_DONG_CD,LV_CD*2 - 2),10,'0')
;