SELECT *
FROM KMIG_NV_CMPX_TYP NCT
WHERE NCT.JOB_ID = 'NVDC006'
AND NCT.EXEC_DTM = '20220418182200'
;

DESC KMIG_NV_CMPX_TYP
;
DESC KRED_NV_cMPX_TYP
;


INSERT KRED_NV_CMPX_TYP
SELECT 
 NV_CMPX_ID
,NV_CMPX_TYP_SEQ
,CMPX_TYP_NM
,SPLY_AREA
,ONLY_AREA
,ONLY_PYNG_NM
,CMPX_TYP_PYNG_NM
,GPLN_CORS
,DOOR_STRC
,ROOM_CNT_STR
,BATH_CNT_STR
,SOH_HSHL_CNT
,SPLY_AREA_NUM
,ONLY_AREA_NUM
,RET_TYP_CD
,AVG_MNTN_AMT
,SMMR_MNTN_AMT
,WNTR_MNTN_AMT
,DEAL_LMIT_YMD
,DEAL_PSBL_YMD
,DCNT_PRC_STR
,REG_USER_ID
,REG_DTM
,CHG_USER_ID
,CHG_DTM
FROM KMIG_NV_CMPX_TYP NCT
WHERE NCT.JOB_ID = 'NVDC006'
AND NCT.EXEC_DTM = '20220418182200'
;