alter table KRED_NV_CMPX modify column cmpl_yymm varchar(8)
;
INSERT KRED_NV_CMPX
SELECT 
 NV_CMPX_ID
,NV_CMPX_NM
,GOV_LEGL_DONG_CD
,NV_CMPX_KND
,BAS_ADDR
,DTL_ADDR
,ROAD_NM_BAS_ADDR
,ROAD_NM_DTL_ADDR
,ADDR
,X_COOR_VAL
,Y_COOR_VAL
,TOT_HSHL_CNT
,TOT_RENT_HSHL_CNT
,TOT_DONG_CNT
,MAX_FLR
,MIN_FLR
,CMPL_YYMM
,SALE_CNT
,JS_CNT
,WS_CNT
,SHRT_RENT_CNT
,BLD_CO_NM
,TOT_PARK_CNT
,HSHL_PER_PARK_CNT
,HEAT_WAY
,HEAT_FUEL
,FAR
,BTLR
,MBIG_SPLY_AREA
,MSML_SPLY_AREA
,CMPX_REG_VAL
,AREA_LST
,MGMT_CO_TEL
,SBWY_INFO
,WASP_PIPE_RPLC
,WHL_DONG_CNT
,BMAK_YN
,MIG_RSN
,REG_USER_ID
,REG_DTM
,CHG_USER_ID
,CHG_DTM
FROM KMIG_NV_CMPX
WHERE JOB_ID = 'NVDC002'
AND EXEC_DTM = '20220418152736'
;
SELECT LENGTH(SALE_CNT)
FROM KMIG_NV_CMPX
WHERE 1=1
#WHERE LENGTH(SALE_CNT) > 3
AND JOB_ID = 'NVDC002'
AND EXEC_DTM = '20220418152736'
;
SELECT COUNT(*)
FROM KMIG_NV_CMPX
WHERE JOB_ID = 'NVDC002'
AND EXEC_DTM = '20220418152736'
;
DESC KMIG_NV_CMPX
;

DESC KRED_NV_CMPX