/* 최상위 코드 MIG*/
INSERT INTO KRED_LEGL_REGN
SELECT GOV_LEGL_DONG_CD     LEGL_REGN_CD
     , LWST_REGN_NM         LEGL_REGN_NM
	 , GOV_LEGL_DONG_NM     WHL_LEGL_REGN_NM
     , UP_GOV_LEGL_DONG_CD  UP_LEGL_REGN_CD
     , '1'                  LV_CD
     , 1000000001           REG_USER_ID
     , NOW()                REG_DTM
     , 1000000001           CHG_USER_ID
     , NOW()                CHG_DTM     
FROM KMIG_GOV_LEGL_DONG
WHERE GOV_LEGL_DONG_CD LIKE '__00000000'
;
/* 세종시 MIG */
INSERT INTO KRED_LEGL_REGN
SELECT '3600000000'         LEGL_REGN_CD
     , LWST_REGN_NM         LEGL_REGN_NM
	 , GOV_LEGL_DONG_NM     WHL_LEGL_REGN_NM
     , UP_GOV_LEGL_DONG_CD  UP_LEGL_REGN_CD
     , '1'                  LV_CD
     , 1000000001           REG_USER_ID
     , NOW()                REG_DTM
     , 1000000001           CHG_USER_ID
     , NOW()                CHG_DTM     
FROM KMIG_GOV_LEGL_DONG
WHERE GOV_LEGL_DONG_CD = '3611000000'
;
UPDATE KRED_LEGL_REGN
SET UP_LEGL_REGN_CD = null
  , CHG_USER_ID = 1000000001
  , CHG_DTM = NOW()
WHERE LV_CD = '1'  
;
/* LV2 */
#INSERT INTO KRED_LEGL_REGN
SELECT GOV_LEGL_DONG_CD     LEGL_REGN_CD
     , LWST_REGN_NM         LEGL_REGN_NM
	 , GOV_LEGL_DONG_NM     WHL_LEGL_REGN_NM
     , CONCAT(SUBSTR(GOV_LEGL_DONG_CD,1,2),'00000000')   UP_LEGL_REGN_CD
     , '2'                  LV_CD
     , 1000000001           REG_USER_ID
     , NOW()                REG_DTM
     , 1000000001           CHG_USER_ID
     , NOW()                CHG_DTM     
FROM KMIG_GOV_LEGL_DONG
WHERE GOV_LEGL_DONG_CD LIKE '_____00000'
#AND GOV_LEGL_DONG_CD NOT IN (SELECT LEGL_REGN_CD FROM KRED_LEGL_REGN)
;
/* LV3 */
INSERT INTO KRED_LEGL_REGN
SELECT GOV_LEGL_DONG_CD     LEGL_REGN_CD
     , LWST_REGN_NM         LEGL_REGN_NM
	 , GOV_LEGL_DONG_NM     WHL_LEGL_REGN_NM
     , CONCAT(SUBSTR(GOV_LEGL_DONG_CD,1,5),'00000')   UP_LEGL_REGN_CD
     , '3'                  LV_CD
     , 1000000001           REG_USER_ID
     , NOW()                REG_DTM
     , 1000000001           CHG_USER_ID
     , NOW()                CHG_DTM     
FROM KMIG_GOV_LEGL_DONG
WHERE 1=1
AND GOV_LEGL_DONG_CD LIKE '________00'
AND GOV_LEGL_DONG_CD NOT IN (SELECT LEGL_REGN_CD FROM KRED_LEGL_REGN)
;
/* LV4 */
INSERT INTO KRED_LEGL_REGN
SELECT GOV_LEGL_DONG_CD     LEGL_REGN_CD
     , LWST_REGN_NM         LEGL_REGN_NM
	 , GOV_LEGL_DONG_NM     WHL_LEGL_REGN_NM
     , CONCAT(SUBSTR(GOV_LEGL_DONG_CD,1,8),'00')   UP_LEGL_REGN_CD
     , '4'                  LV_CD
     , 1000000001           REG_USER_ID
     , NOW()                REG_DTM
     , 1000000001           CHG_USER_ID
     , NOW()                CHG_DTM     
FROM KMIG_GOV_LEGL_DONG
WHERE 1=1
#AND GOV_LEGL_DONG_CD LIKE '________00'
AND GOV_LEGL_DONG_CD NOT IN (SELECT LEGL_REGN_CD FROM KRED_LEGL_REGN)
;
SELECT *
FROM KRED_LEGL_REGN
WHERE LEGL_REGN_CD NOT IN (SELECT GOV_LEGL_DONG_CD FROM KMIG_GOV_LEGL_DONG)
;
SELECT R1.LEGL_REGN_CD,R1.LEGL_REGN_NM,R2.LEGL_REGN_CD,R2.LEGL_REGN_NM,R3.LEGL_REGN_CD,R3.LEGL_REGN_NM,R4.LEGL_REGN_CD,R4.LEGL_REGN_NM  
FROM KRED_LEGL_REGN R1
INNER JOIN KRED_LEGL_REGN R2
ON R1.LEGL_REGN_CD = R2.UP_LEGL_REGN_CD
INNER JOIN KRED_LEGL_REGN R3
ON R2.LEGL_REGN_CD = R3.UP_LEGL_REGN_CD
LEFT OUTER JOIN KRED_LEGL_REGN R4
ON R3.LEGL_REGN_CD = R4.UP_LEGL_REGN_CD
;

SELECT 